# ---
# core:
#   num_workers: 10

# inventory:
#   plugin: nornir.plugins.inventory.simple.SimpleInventory
#   options:
#     hosts_file: ""
#     group_file: ""
#     defaults_file: ""

    
---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "hosts.yaml"
        group_file: ""
        defaults_file: ""
runner:
    plugin: threaded
    options:
        num_workers: 100