# ---
# core:
#   num_workers: 10

# inventory:
#   plugin: nornir.plugins.inventory.simple.SimpleInventory
#   options:
#     hosts_file: ""
#     group_file: ""
#     defaults_file: ""

    
---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/ibi/Documents/Git/Nornir/Blueprints/hosts.yaml"
        group_file: "/home/ibi/Documents/Git/Nornir/Blueprints/groups.yaml"
        defaults_file: "/home/ibi/Documents/Git/Nornir/Blueprints/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 100
