---
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/home/ibi/Documents/Git/Nornir/Blueprints/hosts.yaml"
        group_file: "/home/ibi/Documents/Git/Nornir/Blueprints/groups.yaml"
        defaults_file: "/home/ibi/Documents/Git/Nornir/Blueprints/defaults.yaml"
runner:
    plugin: threaded
    options:
        num_workers: 10
